version: '2'
services:
  kafka:
    image: flozano/kafka:0.9.0.0
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
  webhook:
    build: .
    depends_on:
      - kafka
    ports:
      - "8081:8081"